module.exports = {
  arrowParens: 'avoid',
  endOfLine: 'lf',
  printWidth: 80,
  semi: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
  bracketSameLine: false,
  bracketSpacing: false,
  experimentalOperatorPosition: 'start',
  objectWrap: 'collapse',
  proseWrap: 'always',
};
