#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged (prettier + eslint on staged files)
npm run lint-staged || exit 1

# Run tests for all packages
npm run test --workspaces || exit 1
