name: CI

on:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        working-directory: packages/web
        run: npm run test:install --if-present

      - name: Run checks and tests in parallel
        env:
          CI: true
        run: |
          npx concurrently -n prettier,eslint,ts,api-jest,shared-jest,playwright -c blue,green,magenta,yellow,cyan,red \
            "npm run prettier:check" \
            "npm run lint" \
            "npm run type-check" \
            "npm run -w packages/api test:ci" \
            "npm run -w packages/shared test:ci" \
            "npm run -w packages/web test:ci"

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: packages/web/playwright-report

